export const projects = [
 {slug:'velora',name:'Velora',category:'Ecommerce Website',theme:'velora',headline:'Everyday, elevated.',intro:'A quieter shopping experience for considered everyday objects.',focus:'Turn a broad product collection into an effortless path from discovery to checkout.',approach:'A calm visual hierarchy, generous product space and a purchase journey with fewer distractions.',outcome:'A responsive storefront concept that brings the products forward and keeps the next step clear.',tags:['Art direction','Ecommerce UX','Responsive design']},
 {slug:'fitly',name:'Fitly',category:'Mobile App',theme:'fitly',headline:'Made to move.',intro:'A little clarity. A little momentum. A better everyday routine.',focus:'Help people understand their activity without turning every day into a wall of numbers.',approach:'Prioritise the daily summary, make progress readable and keep the interface encouraging.',outcome:'A mobile product concept with focused activity views and a simple visual rhythm.',tags:['Product strategy','Mobile UI','Interaction design']},
 {slug:'zentra',name:'Zentra',category:'SaaS Platform',theme:'zentra',headline:'A clearer view.',intro:'Essential business signals, brought into one focused workspace.',focus:'Make a complex business overview easier to scan, interpret and act on.',approach:'Give important metrics a consistent home, then layer in context only where it supports a decision.',outcome:'A dashboard concept organised around clarity, useful comparisons and the next action.',tags:['UX architecture','Dashboard design','Data visualisation']},
 {slug:'blume',name:'Blume',category:'Brand & Website',theme:'blume',headline:'Room to grow.',intro:'An editorial identity for a slower, more beautiful everyday.',focus:'Give an emerging lifestyle brand a distinctive digital voice without overwhelming its collection.',approach:'Let spacious typography, measured pacing and a restrained palette create recognition.',outcome:'A brand and website concept with a coherent identity from first impression to product discovery.',tags:['Brand identity','Art direction','Web design']}
];
export const services = [
 {slug:'websites',name:'Website Design & Development',short:'Websites',line:'Your best first impression.',intro:'Responsive, conversion-focused websites that give your brand room to stand out.',deliverables:['Website strategy & structure','Responsive UI/UX design','Frontend development','Performance & launch checks'],steps:[['Understand','Start with your audience, content and business goals.'],['Design','Build a clear visual hierarchy and a journey that feels natural.'],['Develop','Turn the design into a responsive, usable experience and prepare for launch.']]},
 {slug:'apps',name:'App Design & Development',short:'Apps',line:'Useful from the first tap.',intro:'Thoughtful mobile products designed around the things people do every day.',deliverables:['Product discovery','User journeys & wireframes','Mobile interface design','Interactive prototyping'],steps:[['Find the core','Identify the task your product needs to make easier.'],['Shape the flow','Remove unnecessary steps and give every interaction a clear purpose.'],['Make it feel right','Refine feedback, accessibility and the details that build confidence.']]},
 {slug:'seo',name:'SEO & Growth',short:'SEO',line:'Made to be found.',intro:'Strong technical foundations and useful content that connect your business with the right searches.',deliverables:['Technical SEO review','Search intent mapping','Content structure','Measurement plan'],steps:[['Audit','Understand the website’s technical foundations and existing content.'],['Prioritise','Focus effort on the issues and opportunities that matter most.'],['Improve','Make considered changes, review performance and keep refining.']]},
 {slug:'marketing',name:'Digital & Performance Marketing',short:'Marketing',line:'Attention with direction.',intro:'Campaign strategy, creative direction and measurement built around meaningful business goals.',deliverables:['Campaign planning','Creative direction','Audience strategy','Reporting framework'],steps:[['Define the goal','Agree what success means before choosing a channel.'],['Create the connection','Develop messages and creative that make the offer clear.'],['Learn & refine','Use campaign feedback to improve the next round of decisions.']]}
];
export const articles = [
 {slug:'websites-business-growth',category:'Strategy',title:'How Great Websites Drive Real Business Growth',cover:'Beyond the homepage.',time:'6 min read',intro:'Good design earns attention. A clear journey turns that attention into action.',chapters:[['Give every page a job','Start with the questions your visitors bring. Explain the offer, provide the context they need and make the next step easy to recognise. A strong page has a purpose that can be understood without a long introduction.'],['Build confidence before asking','Clarity, consistent visual language and useful detail work together. Show what you do, explain how it works and make the experience comfortable on smaller screens. Use genuine evidence when it is available.'],['Measure the meaningful steps','Define the actions that matter to the business, such as a qualified enquiry or a completed purchase. Look for friction in the journey and improve one problem at a time. Design is a process of learning, not a one-off decoration.']]},
 {slug:'thoughtful-ui-ux',category:'Design',title:'Top UI/UX Trends to Watch',cover:'Less friction. More feeling.',time:'5 min read',intro:'The most useful direction in interface design is also the simplest: make the experience easier to understand.',chapters:[['A hierarchy that does the work','A clear hierarchy helps people find their way without reading everything. Use size, spacing and contrast consistently. Keep important controls familiar and make their outcomes predictable.'],['Motion that explains change','Movement is useful when it connects one state to another. A short transition can show where content came from, while a subtle reveal can guide attention. Give people control and respect reduced-motion preferences.'],['A little less, done better','Removing a step can be more valuable than adding a feature. Review forms, menus and decision points with the user’s task in mind. Make the essential journey work well before adding extra complexity.']]},
 {slug:'seo-foundations',category:'Growth',title:'SEO That Actually Works',cover:'Made to be found.',time:'7 min read',intro:'A useful website is a stronger starting point than a collection of shortcuts.',chapters:[['Make the foundations reliable','Organise pages around clear topics and make them easy to navigate. Check that important content is accessible, links work and the experience remains usable across devices. Technical work should help people as well as crawlers.'],['Answer a real question','Write for the people you want to reach. Understand what they need to know, then offer a clear, specific answer. Avoid repeating the same content across many pages simply to target variations of a phrase.'],['Keep learning','Review which pages are useful and which need improvement. Maintain existing content, resolve issues and look for gaps in the journey. Sustainable growth starts with a website worth visiting.']]}
];
export const quotes = ['Stackfry understood our vision and turned it into a product that actually moves our business forward.','The process felt collaborative from the first conversation. Every detail had a clear purpose.','A thoughtful team, a clear process, and a digital experience we’re excited to share.'];
export const routeList=['/','/work','/services','/about','/blog','/contact',...projects.map(p=>'/work/'+p.slug),...services.map(s=>'/services/'+s.slug),...articles.map(a=>'/blog/'+a.slug)];
