import React,{useEffect,useLayoutEffect,useRef,useState,createContext,useContext} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,Link,NavLink,useLocation,useNavigate,useParams} from 'react-router-dom';
import {projects,services,articles,quotes} from './data.js';
import homeHTML from './home.html';
import './base.css';
import './pages.css';

const MotionContext=createContext();
const navItems=['Work','Services','About','Blog','Contact'];
const Arrow=()=> <span aria-hidden="true">↗</span>;
function Button({to='/contact',children='Start a Project'}){return <Link className="button" to={to}>{children}<Arrow/></Link>;}
function Eyebrow({children}){return <div className="eyebrow">{children}</div>;}
function Title({label,first,accent,copy}){return <section className="wrap page-intro"><div className="intro-copy"><Eyebrow>{label}</Eyebrow><h1><span className="title-line">{first}</span><span className="title-line lime">{accent}</span></h1>{copy&&<p>{copy}</p>}</div><div className="intro-bottom"><span>STACKFRY / WE COOK DIGITAL PRODUCTS.</span><a href="#next">SCROLL TO DISCOVER ↓</a></div></section>;}
function CTA({title='Let’s cook something amazing.'}){return <section className="contact-section"><div className="wrap reveal"><Eyebrow>SOMETHING GOOD STARTS WITH A CONVERSATION.</Eyebrow><h2>Have an idea?<br/><span className="lime">{title}</span></h2><p>Tell us what you’re building. We’ll help turn the idea into a product people love.</p><Button/></div><div className="contact-line" aria-hidden="true"/></section>;}
function Header(){const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);const location=useLocation();useEffect(()=>{setOpen(false);},[location.pathname]);useEffect(()=>{const update=()=>setScrolled(scrollY>35);update();addEventListener('scroll',update,{passive:true});const key=e=>{if(e.key==='Escape')setOpen(false);};addEventListener('keydown',key);return()=>{removeEventListener('scroll',update);removeEventListener('keydown',key);};},[]);return <><a className="skip" href="#page-content">Skip to content</a><header className={scrolled?'scrolled':''}><Link className="brand" to="/">stackfry<sup>®</sup></Link><nav aria-label="Main navigation" className={open?'open':''}>{navItems.map(n=><NavLink key={n} to={'/'+n.toLowerCase()}>{n}</NavLink>)}</nav><Link className="button nav-cta" to="/contact">Start a Project <Arrow/></Link><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?'Close navigation':'Open navigation'}>Menu <span>{open?'×':'☰'}</span></button></header></>;}
function Footer(){const {paused,toggle}=useContext(MotionContext);return <footer className="wrap"><div className="footer-grid"><div><Link className="brand" to="/">stackfry<sup>®</sup></Link><p>We Cook Digital Products.</p><p>Independent minds.<br/>Shared ambition.</p></div><div><h4>EXPLORE</h4>{navItems.map(n=><Link key={n} to={'/'+n.toLowerCase()}>{n}</Link>)}</div><div><h4>EXPERTISE</h4>{services.map(s=><Link key={s.slug} to={'/services/'+s.slug}>{s.name}</Link>)}</div><div><h4>LET’S CONNECT</h4><Link to="/contact">Start a conversation ↗</Link><button onClick={()=>window.scrollTo({top:0,behavior:paused?'instant':'smooth'})}>Back to top ↑</button><button aria-pressed={paused} onClick={toggle}>{paused?'Play animations ▷':'Pause animations Ⅱ'}</button></div></div><div className="footer-baseline"><span>© 2026 Stackfry. All rights reserved.</span><span>Interactive concept prototype</span></div></footer>;}
function Ambient(){return <div className="ambient" aria-hidden="true"><div className="ambient-wash one"/><div className="ambient-wash two"/><div className="ambient-grid"/></div>;}
function Desktop(){return <div className="desktop"><div className="mini-nav">V E L O R A <span>MENU ↗</span></div><div className="desktop-title">Everyday,<br/>elevated.</div><div className="swatches"><div/><div/><div/></div></div>;}
function Phone(){return <div className="phone"><b>fitly.</b><div>Your daily<br/>energy.</div><div className="activity"><strong>8,420</strong><small>STEPS TODAY</small><div className="activity-bars">{Array.from({length:6},(_,i)=><i key={i}/>)}</div></div><small>Keep moving ↗</small></div>;}
function ProductVisual({project}){return <div className={'project-image '+project.theme}>{project.slug==='velora'?<Desktop/>:project.slug==='fitly'?<Phone/>:project.slug==='zentra'?<div className="dashboard"><div className="mini-nav">zentra / Overview</div><h4>A clearer view.</h4><small>Revenue this month</small><strong>₹ 8,42,000</strong><div className="chart" aria-hidden="true">{Array.from({length:10},(_,i)=><i key={i}/>)}</div></div>:<div className="blume-mark"><span>b l u m e</span><small>ROOM TO GROW.</small><p>Objects for a slower, more beautiful everyday.</p></div>}<span className="project-hover">Explore concept ↗</span></div>;}
function ProjectGrid(){return <div className="portfolio-grid">{projects.map((p,i)=><Link key={p.slug} className={'project reveal '+([0,3].includes(i)?'wide':'')} to={'/work/'+p.slug}><ProductVisual project={p}/><div className="project-meta"><h3>{p.name}</h3><span>{p.category} ↗</span></div></Link>)}</div>;}
function Carousel(){const {paused}=useContext(MotionContext);const [stopped,setStopped]=useState(false);const ref=useRef();useEffect(()=>{if(!window.gsap||paused)return;const animation=gsap.to(ref.current,{xPercent:-50,duration:26,ease:'none',repeat:-1,paused:stopped});return()=>animation.revert();},[paused,stopped]);return <section className="logo-section" aria-label="Portfolio logo carousel"><div className="wrap logo-heading"><Eyebrow>PORTFOLIO BRANDS / CONCEPT PROJECTS</Eyebrow><button onClick={()=>setStopped(!stopped)} aria-pressed={stopped} disabled={paused}>{paused?'Motion paused':stopped?'Play ▷':'Pause Ⅱ'}</button></div><div className="logo-window"><div className="logo-track" ref={ref}>{[0,1].map(i=><div key={i} className="logo-group" aria-hidden={i===1?true:undefined}>{['velora','fitly.','ZENTRA','blume®','Layers'].map(n=><span key={n}>{n}</span>)}</div>)}</div></div></section>;}
function StoryFlow({label='HOW WE THINK',title='From a spark.\nTo something real.',steps,words=['Discover.','Create.','Grow.']}){return <section className="story-section wrap"><div className="reveal story-heading"><Eyebrow>{label}</Eyebrow><h2>{title.split('\n').map((l,i)=><React.Fragment key={l}>{i>0&&<br/>}{l}</React.Fragment>)}</h2></div><div className="scroll-story"><div className="story-sticky"><div className="story-stage" aria-hidden="true"><div className="story-stage-grid"/>{steps.map((s,i)=><div key={i} className={'story-panel '+(i===0?'is-active':'')}><span className="story-count">0{i+1}</span><div className="story-word">{words[i]||s[0]}</div><div className="story-rule"/><small>{label} / 0{i+1}</small></div>)}</div><div className="story-dots" aria-hidden="true">{steps.map((_,i)=><span key={i} className={i===0?'is-active':''}/>)}</div></div><div className="story-chapters">{steps.map(([heading,copy],i)=><article className="story-chapter" data-step={i} key={heading}><Eyebrow>0{i+1} / {heading.toUpperCase()}</Eyebrow><h3 className="read-reveal">{heading}</h3><p>{copy}</p><div className="chapter-line"/></article>)}</div></div></section>;}
const homeSteps=[['Find the right idea','A strong product starts with the right question. We align audience needs, business goals and the experience you want to create.'],['Make every detail count','We bring structure, design and technology together. Each decision has a purpose, from the first screen to the final interaction.'],['Keep making it better','Launch is a starting point. We use what we learn to refine the experience and support the next stage of growth.']];
function Home(){const navigate=useNavigate();const ref=useRef();const {paused}=useContext(MotionContext);const [q,setQ]=useState(0);const split=homeHTML.indexOf('<section class="contact-section"');const markup=homeHTML.slice(0,split);useEffect(()=>{const root=ref.current;const quote=root.querySelector('#quote');if(quote){quote.textContent=quotes[q];root.querySelector('#quote-index').textContent=`0${q+1} / 03`;if(window.gsap&&!paused)gsap.fromTo(quote,{opacity:0,y:8},{opacity:1,y:0,duration:.45});}},[q,paused]);function click(e){const btn=e.target.closest('button');const a=e.target.closest('a');if(a&&a.getAttribute('href')?.startsWith('/')&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey&&e.button===0){e.preventDefault();navigate(a.getAttribute('href'));return;}if(!btn)return;if(btn.dataset.project){navigate('/work/'+btn.dataset.project.toLowerCase());}else if(btn.dataset.service){const s=services.find(s=>s.name===btn.dataset.service);navigate('/services/'+(s?.slug||'websites'));}else if(btn.dataset.article){navigate('/blog/'+articles[Number(btn.dataset.article)].slug);}else if(btn.id==='quote-prev'){setQ(v=>(v+2)%3);}else if(btn.id==='quote-next'){setQ(v=>(v+1)%3);}else if(btn.id==='carousel-toggle'){const tweens=window.gsap?.getTweensOf(rootCarousel())||[];const p=btn.dataset.paused!=='true';btn.dataset.paused=String(p);btn.textContent=p?'Play ▷':'Pause Ⅱ';btn.setAttribute('aria-label',p?'Play logo carousel':'Pause logo carousel');tweens.forEach(t=>t.paused(p));} }function rootCarousel(){return ref.current.querySelector('.logo-track');}return <><div className="home-markup" ref={ref} onClick={click} dangerouslySetInnerHTML={{__html:markup}}/><StoryFlow steps={homeSteps}/><CTA/></>;}
function Work(){return <><Title label="OUR WORK / SELECTED CONCEPTS" first="Ideas made" accent="tangible." copy="Four explorations in design, technology and the details that make a product feel right."/><section className="work-section section" id="next"><div className="wrap"><ProjectGrid/></div></section><StoryFlow label="THE THINKING BEHIND THE WORK" title={'Clarity first.\nCharacter always.'} steps={[["Start with the challenge","Before a visual direction comes a clear purpose. Every concept begins with the experience it needs to improve."],["Give the idea a voice","We connect the interface, typography and interaction into a visual language that belongs to the product."],["Make it work together","The experience should feel coherent across screens, states and devices. The details matter as much as the first impression."]]} words={['Purpose.','Character.','Coherence.']}/><Carousel/><CTA/></>;}
function WorkDetail(){const {slug}=useParams();const p=projects.find(p=>p.slug===slug);if(!p)return <NotFound/>;const next=projects[(projects.indexOf(p)+1)%projects.length];return <><Title label={'CONCEPT PROJECT / '+p.category.toUpperCase()} first={p.name} accent={p.headline} copy={p.intro}/><section className="wrap case-showcase reveal" id="next"><ProductVisual project={p}/><div className="case-meta"><p>Independent design exploration. Not a completed client engagement.</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></section><StoryFlow label={'INSIDE '+p.name.toUpperCase()} title={'The thought.\nThe experience.'} steps={[["The focus",p.focus],["The approach",p.approach],["The concept",p.outcome]]} words={['Focus.','Craft.','Experience.']}/><section className="wrap next-project reveal"><Eyebrow>NEXT EXPLORATION</Eyebrow><Link to={'/work/'+next.slug}><h2>{next.name} <Arrow/></h2></Link><Link className="text-link" to="/work">← All work</Link></section><CTA/></>;}
function Services(){return <><Title label="WHAT WE DO" first="From idea" accent="to real growth." copy="Strategy, design, technology and growth. Built around what your business needs next."/><section className="wrap service-list" id="next">{services.map((s,i)=><Link to={'/services/'+s.slug} className="service-row reveal" key={s.slug}><span className="service-number">0{i+1}</span><div><h2>{s.name}</h2><p>{s.intro}</p><div className="tags">{s.deliverables.slice(0,3).map(d=><span key={d}>{d}</span>)}</div></div><span className="service-link-arrow">↗</span></Link>)}</section><StoryFlow label="ONE CONNECTED PROCESS" title={'Thoughtfully made.\nFrom start to finish.'} steps={homeSteps}/><CTA/></>;}
function ServiceDetail(){const {slug}=useParams();const s=services.find(s=>s.slug===slug);if(!s)return <NotFound/>;return <><Title label={s.name.toUpperCase()} first={s.line.split(' ').slice(0,2).join(' ')} accent={s.line.split(' ').slice(2).join(' ')} copy={s.intro}/><section className="wrap deliverables section" id="next"><div className="reveal"><Eyebrow>WHAT WE CAN HELP WITH</Eyebrow><h2>A clear scope.<br/>A considered result.</h2><p>We shape the engagement around your priorities, your product and the stage of your business.</p></div><div>{s.deliverables.map((d,i)=><div className="deliverable reveal" key={d}><span>0{i+1}</span><h3>{d}</h3></div>)}</div></section><StoryFlow label="HOW WE GET THERE" title={'Good questions.\nBetter outcomes.'} steps={s.steps} words={s.steps.map(s=>s[0]+'.')}/><section className="wrap service-summary reveal"><Eyebrow>LET’S TALK ABOUT YOUR PROJECT</Eyebrow><h2>{s.short}, with purpose.</h2><p>Share what you have in mind. We’ll help define the right next step.</p><Button to={'/contact?service='+encodeURIComponent(s.name)}>Discuss this service</Button><Link className="text-link" to="/services">← All services</Link></section><CTA/></>;}
function Testimonials(){const [q,setQ]=useState(0);return <section className="wrap section"><Eyebrow>CLIENT STORIES / SAMPLE CONTENT</Eyebrow><h2>Built on lasting<br/>partnerships.</h2><div className="story-grid"><div className="quote-card reveal"><span className="quote-mark">“</span><blockquote key={q} className="quote-text">{quotes[q]}</blockquote><Eyebrow>CLIENT NAME / FOUNDER, COMPANY</Eyebrow><small>Sample testimonial — replace with an approved client story.</small></div><div className="story-copy reveal"><h3>Good work starts<br/>with good people.</h3><p>We bring care, clarity and shared ambition to every step of the journey.</p><div className="quote-controls"><button aria-label="Previous sample testimonial" onClick={()=>setQ((q+2)%3)}>←</button><span aria-live="polite">0{q+1} / 03</span><button aria-label="Next sample testimonial" onClick={()=>setQ((q+1)%3)}>→</button></div></div></div></section>;}
function About(){return <><Title label="THE STUDIO" first="Independent minds." accent="Shared ambition." copy="Stackfry brings design, development and growth together to turn bold ideas into thoughtful digital products."/><section className="wrap manifesto section" id="next"><Eyebrow>WE COOK DIGITAL PRODUCTS.</Eyebrow><p className="manifesto-text">A good idea deserves<br/><span className="lime">care, curiosity</span><br/>and the right ingredients.</p><div className="manifesto-caption"><span>OUR APPROACH</span><p>We believe the best digital experiences balance a clear purpose with a distinct point of view. We ask questions, work closely and make every detail count.</p></div></section><StoryFlow label="WHAT MATTERS TO US" title={'The way we think.\nThe way we work.'} steps={[["Clarity before complexity","We look for the simplest useful solution. A clear idea helps everyone make better decisions throughout the project."],["Craft with a purpose","We care about how a product looks, feels and works. Thoughtful design makes the experience more useful, not just more decorative."],["Partnership over handoffs","We work with you throughout the process. Shared context and honest conversations help create a result everyone understands."]]} words={['Clarity.','Craft.','Together.']}/><Testimonials/><CTA/></>;}
function BlogCards(){return <div className="blog-grid">{articles.map((a,i)=><Link className="blog-card reveal" to={'/blog/'+a.slug} key={a.slug}><div className="blog-cover"><small>STACKFRY JOURNAL / 0{i+1}</small><h3>{a.cover}</h3><span>↗</span></div><small>{a.category.toUpperCase()} / {a.time.toUpperCase()}</small><h4>{a.title} ↗</h4></Link>)}</div>;}
function Blog(){return <><Title label="THE STACKFRY JOURNAL" first="Ideas, insights" accent="& what’s next." copy="Notes on building better digital experiences, from the first idea to the next stage of growth."/><section className="work-section section" id="next"><div className="wrap"><BlogCards/><p className="content-note">Sample editorial content for this prototype.</p></div></section><StoryFlow label="A FEW THINGS WE BELIEVE" title={'Useful ideas.\nWorth thinking about.'} steps={[["Make it clear","A website should answer questions and help people move forward. Clear thinking comes before visual complexity."],["Make it feel natural","Good interaction design respects attention. Every transition should explain a change, not compete with the content."],["Keep improving","Digital products are never truly finished. There is always something to learn from the people who use them."]]} words={['Clarity.','Feeling.','Progress.']}/><CTA/></>;}
function Article(){const {slug}=useParams();const a=articles.find(a=>a.slug===slug);if(!a)return <NotFound/>;const next=articles[(articles.indexOf(a)+1)%articles.length];return <><section className="wrap article-intro"><Link className="text-link" to="/blog">← The journal</Link><Eyebrow>{a.category.toUpperCase()} / {a.time.toUpperCase()} / SAMPLE ARTICLE</Eyebrow><h1>{a.title}</h1><p>{a.intro}</p></section><div className="wrap article-layout" id="next"><aside><Eyebrow>IN THIS ARTICLE</Eyebrow>{a.chapters.map(([title],i)=><a className="article-toc" key={title} href={'#chapter-'+i}>0{i+1} / {title}</a>)}</aside><div>{a.chapters.map(([title,text],i)=><section className="article-chapter" id={'chapter-'+i} key={title}><Eyebrow>0{i+1}</Eyebrow><h2 className="read-reveal">{title}</h2><p className="reveal">{text}</p><div className="chapter-line"/></section>)}</div></div><section className="wrap next-project reveal"><Eyebrow>KEEP READING</Eyebrow><Link to={'/blog/'+next.slug}><h2>{next.title} ↗</h2></Link><Link className="text-link" to="/blog">← All articles</Link></section><CTA/></>;}
function Contact(){const location=useLocation();const initialService=new URLSearchParams(location.search).get('service')||'';const [status,setStatus]=useState('');function submit(e){e.preventDefault();const d=new FormData(e.currentTarget);const text=`STACKFRY — PROJECT BRIEF\n\nName: ${d.get('name')}\nEmail: ${d.get('email')}\nService: ${d.get('service')||'Let’s decide together'}\n\nProject idea:\n${d.get('idea')}\n\nCreated in the Stackfry prototype. Not submitted.`;const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='Stackfry-project-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);setStatus('Your brief is ready to keep or share. No information has been sent.');}return <><Title label="LET’S START A CONVERSATION" first="Your next idea." accent="Our next obsession." copy="Tell us what you’re building, what you want to change, or where you need a fresh perspective."/><section className="wrap contact-layout section" id="next"><div className="contact-sticky reveal"><Eyebrow>A GOOD PLACE TO START</Eyebrow><h2>Big plans.<br/>Small details.<br/><span className="lime">All welcome.</span></h2><p>Put your thoughts into a short brief. It doesn’t need to be perfect to start something good.</p><div className="contact-note">This prototype creates a downloadable brief. It does not send your details to Stackfry.</div></div><form className="brief-form reveal" onSubmit={submit}><div className="form-heading"><Eyebrow>YOUR PROJECT / THE FIRST INGREDIENTS</Eyebrow><span>01—04</span></div><label htmlFor="name">01 / What’s your name?</label><input id="name" name="name" autoComplete="name" required maxLength={100} placeholder="Your name"/><label htmlFor="email">02 / Your email address</label><input id="email" type="email" name="email" autoComplete="email" required maxLength={200} placeholder="you@company.com"/><label htmlFor="service">03 / What can we help with?</label><select id="service" name="service" defaultValue={initialService}><option value="">Let’s decide together</option>{services.map(s=><option key={s.slug}>{s.name}</option>)}</select><label htmlFor="idea">04 / Tell us a little about your idea</label><textarea id="idea" name="idea" rows={5} required maxLength={4000} placeholder="The idea, the challenge, the ambition…"/><button className="button" type="submit">Download my brief <span>↓</span></button><p role="status" className="form-status">{status}</p></form></section><StoryFlow label="WHAT COMES NEXT" title={'A conversation.\nThen a clear direction.'} steps={[["Share the idea","Gather your goals, priorities and any references that help explain what you have in mind."],["Define the shape","Agree the scope, deliverables and the right approach for your project before moving forward."],["Make it happen","Bring the experience to life through a collaborative process, with room for feedback along the way."]]} words={['Talk.','Plan.','Create.']}/></>;}
function NotFound(){return <section className="wrap page-intro not-found"><Eyebrow>404 / A SMALL DETOUR</Eyebrow><h1>This page<br/><span className="lime">isn’t on the menu.</span></h1><p>Let’s get you back to something good.</p><Button to="/">Back to the studio</Button></section>;}

function MotionEngine({children}){const location=useLocation();const [paused,setPaused]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);const ref=useRef();const initial=useRef(true);const animatedPath=useRef(null);useEffect(()=>{const query=matchMedia('(prefers-reduced-motion: reduce)');const change=e=>setPaused(e.matches);query.addEventListener('change',change);return()=>query.removeEventListener('change',change);},[]);
 useLayoutEffect(()=>{if(animatedPath.current!==location.pathname){window.scrollTo({top:0,left:0,behavior:'instant'});animatedPath.current=location.pathname;}document.body.classList.toggle('reduced-motion',paused);if(!window.gsap||!window.ScrollTrigger)return;gsap.registerPlugin(ScrollTrigger);let refreshFrame;const ctx=gsap.context(()=>{if(paused)return;
  gsap.from('.route-page',{opacity:0,y:12,duration:.55,ease:'power2.out',clearProps:'transform'});
  gsap.from('.title-line,.article-intro h1',{y:55,opacity:0,duration:1,stagger:.1,ease:'power3.out'});
  gsap.from('.intro-copy>.eyebrow,.intro-copy>p,.intro-bottom',{opacity:0,y:18,duration:.8,stagger:.12,delay:.15});
  if(document.querySelector('.line>span')){gsap.from('.line>span',{yPercent:110,duration:1.1,stagger:.1,ease:'power3.out'});gsap.from('.hero-enter',{opacity:0,y:20,duration:.8,stagger:.1});gsap.to('.float-desktop',{y:-13,rotation:4,duration:4,repeat:-1,yoyo:true,ease:'sine.inOut'});gsap.to('.float-phone',{y:12,rotation:-5,duration:3.5,repeat:-1,yoyo:true,ease:'sine.inOut'});gsap.to('.home-markup .logo-track',{xPercent:-50,duration:26,ease:'none',repeat:-1,paused:document.querySelector('#carousel-toggle')?.dataset.paused==='true'});}
  gsap.to('.ambient-wash.one',{x:'12vw',y:'8vh',scale:1.2,duration:18,yoyo:true,repeat:-1,ease:'sine.inOut'});gsap.to('.ambient-wash.two',{x:'-15vw',y:'-10vh',scale:.8,duration:23,yoyo:true,repeat:-1,ease:'sine.inOut'});
  gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{opacity:0,y:35,duration:.85,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 94%',once:true}}));
  gsap.utils.toArray('.project-image').forEach(el=>{if(el.firstElementChild)gsap.fromTo(el.firstElementChild,{y:-18},{y:18,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:1.2}});});
  gsap.utils.toArray('.read-reveal').forEach(el=>gsap.fromTo(el,{opacity:.35,y:12},{opacity:1,y:0,ease:'none',scrollTrigger:{trigger:el,start:'top 90%',end:'top 40%',scrub:.7}}));
  gsap.utils.toArray('.chapter-line').forEach(el=>gsap.from(el,{scaleX:0,transformOrigin:'left',ease:'none',scrollTrigger:{trigger:el.parentElement,start:'top 80%',end:'bottom 55%',scrub:.8}}));
  gsap.utils.toArray('.scroll-story').forEach(story=>{const panels=story.querySelectorAll('.story-panel'),dots=story.querySelectorAll('.story-dots span');const activate=index=>{panels.forEach((p,i)=>p.classList.toggle('is-active',i===index));dots.forEach((p,i)=>p.classList.toggle('is-active',i===index));};story.querySelectorAll('.story-chapter').forEach((chapter,i)=>{ScrollTrigger.create({trigger:chapter,start:'top 58%',end:'bottom 58%',onEnter:()=>activate(i),onEnterBack:()=>activate(i)});});});
  gsap.utils.toArray('.article-chapter').forEach((chapter,i)=>ScrollTrigger.create({trigger:chapter,start:'top 45%',end:'bottom 45%',onToggle:s=>{const links=document.querySelectorAll('.article-toc');if(s.isActive)links.forEach((a,j)=>a.classList.toggle('is-active',i===j));}}));
  gsap.utils.toArray('[data-count]').forEach(el=>{const obj={value:0};gsap.to(obj,{value:+el.dataset.count,duration:1.8,ease:'power2.out',onUpdate:()=>el.textContent=Math.round(obj.value)+el.dataset.suffix,scrollTrigger:{trigger:el,start:'top 95%',once:true}});});
  gsap.utils.toArray('.chart').forEach(el=>gsap.from(el.children,{scaleY:.05,transformOrigin:'bottom',stagger:.06,duration:1,scrollTrigger:{trigger:el,start:'top 90%',once:true}}));
  gsap.utils.toArray('.contact-line').forEach(el=>gsap.from(el,{scaleX:0,ease:'none',scrollTrigger:{trigger:el.parentElement,start:'top 90%',end:'bottom bottom',scrub:1}}));
  refreshFrame=requestAnimationFrame(()=>ScrollTrigger.refresh());
 },ref);return()=>{cancelAnimationFrame(refreshFrame);ctx.revert();};},[location.pathname,paused]);
 useLayoutEffect(()=>{window.scrollTo({top:0,left:0,behavior:'instant'});const parts=location.pathname.split('/').filter(Boolean);const detail=projects.find(p=>p.slug===parts[1])||services.find(p=>p.slug===parts[1])||articles.find(p=>p.slug===parts[1]);document.title=(detail?.title||detail?.name|| (parts[0]?parts[0][0].toUpperCase()+parts[0].slice(1):'We Cook Digital Products.'))+' — Stackfry';if(!initial.current)document.querySelector('#page-content')?.focus({preventScroll:true});initial.current=false;},[location.pathname]);
 useEffect(()=>{const progress=document.querySelector('.progress');const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?scrollY/max:0})`;};addEventListener('scroll',update,{passive:true});update();return()=>removeEventListener('scroll',update);},[location.pathname]);
 useEffect(()=>{if(paused)return;const art=document.querySelector('.hero-art');if(!art||!window.gsap)return;const target=art.querySelector('.hero-parallax');const move=e=>{if(e.pointerType==='touch')return;const r=art.getBoundingClientRect();gsap.to(target,{x:((e.clientX-r.left)/r.width-.5)*16,y:((e.clientY-r.top)/r.height-.5)*16,duration:.8});};const leave=()=>gsap.to(target,{x:0,y:0,duration:.8});art.addEventListener('pointermove',move);art.addEventListener('pointerleave',leave);return()=>{art.removeEventListener('pointermove',move);art.removeEventListener('pointerleave',leave);gsap.killTweensOf(target);gsap.set(target,{clearProps:'transform'});};},[location.pathname,paused]);
 return <MotionContext.Provider value={{paused,toggle:()=>setPaused(v=>!v)}}><div ref={ref}><div className="progress" aria-hidden="true"/><Ambient/>{children}</div></MotionContext.Provider>;}
function App(){const location=useLocation();return <MotionEngine><Header/><main id="page-content" tabIndex={-1}><div className="route-page" key={location.pathname}><Routes><Route path="/" element={<Home/>}/><Route path="/work" element={<Work/>}/><Route path="/work/:slug" element={<WorkDetail/>}/><Route path="/services" element={<Services/>}/><Route path="/services/:slug" element={<ServiceDetail/>}/><Route path="/about" element={<About/>}/><Route path="/blog" element={<Blog/>}/><Route path="/blog/:slug" element={<Article/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></div></main><Footer/></MotionEngine>;}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
